---
- name: update images
  hosts: all
  become: yes
  vars_files:
  - host_vars/main.yml

  roles:
  - geerlingguy.docker
  - install-dependent
  - install_docker_registry
  - load_images
  - push_images