- name: push starlingx images to local registry
  docker_image:
    name: "{{local_registry}}/{{item[0]}}"
    tag: "{{item[1]}}"
    push: yes
    source: local
  with_nested: 
    - "{{images.starlingx.names}}"
    - "{{images.starlingx.tags}}"

- name: push docker.io images to local registry
  docker_image:
    name: "{{local_registry}}/{{item | regex_replace('(docker.io)/')}}"
    push: yes
    source: local
  with_items: 
    - "{{images.docker}}"

- name: push quay.io images to local registry
  docker_image:
    name: "{{local_registry}}/{{item | regex_replace('(quay.io)/')}}"
    push: yes
    source: local
  with_items: 
    - "{{images.quay}}"

- name: push gcr.io images to local registry
  docker_image:
    name: "{{local_registry}}/{{item | regex_replace('gcr.io/')}}"
    push: yes
    source: local
  with_items: 
    - "{{images.gcr}}"

- name: Tag and push k8s.gcr.io images to local registry
  docker_image:
    name: "{{local_registry}}/{{item | regex_replace('k8s.gcr.io/')}}"
    push: yes
    source: local
  with_items: 
    - "{{images.k8s}}"