---
- name: remove old starlingx images
  docker_image:
    name: "{{ docker_registry + item[0]}}"
    tag: "{{item[1]}}"
    state: absent
  with_nested: 
    - "{{images.starlingx.names}}"
    - "{{images.starlingx.tags[0]}}"
  when: clean_images

- name: pull starlingx images
  docker_image:
    name: "{{ docker_registry + item[0]}}"
    tag: "{{item[1]}}"
    repository: "{{local_registry}}/{{item[0]}}"
    source: pull
  with_nested: 
    - "{{images.starlingx.names}}"
    - "{{images.starlingx.tags}}"

- name: pull docker.io images
  docker_image:
    name: "{{item}}"
    repository: "{{local_registry}}/{{item | regex_replace('(docker.io)/')}}"
    source: pull
  with_items: 
    - "{{images.docker}}"

- name: pull quay.io images
  docker_image:
    name: "{{ quay_registry + item | regex_replace('quay.io/')}}"
    repository: "{{local_registry}}/{{item | regex_replace('(quay.io)/')}}"
    source: pull
  with_items: 
    - "{{images.quay}}"


- name: pull gcr.io images
  docker_image:
    name: "{{ gcr_registry + item | regex_replace('gcr.io/')}}"
    repository: "{{local_registry}}/{{item | regex_replace('gcr.io/')}}"
    source: pull
  with_items: 
    - "{{images.gcr}}"

- name: pull k8s.gcr.io images
  docker_image:
    name: "{{ k8s_registry + item | regex_replace('k8s.gcr.io/')}}"
    repository: "{{local_registry}}/{{item | regex_replace('k8s.gcr.io/')}}"
    source: pull
  with_items: 
    - "{{images.k8s}}"