---
- name: upload images
  hosts: local
  gather_facts: no
  vars_files:
  - host_vars/stx_images.yml
  - host_vars/registry.yml

  tasks:

  - debug: var=images

  - debug: var=gcr_registry

  - name: Install Docker Service
    become: yes
    apt: name=docker update_cache=yes

  - name: install python-pip
    become: yes
    apt: name={{ item }}
    with_items:
      - python-pip
  
  - name: Upgrade pip
    pip:
      name: pip
      extra_args: --upgrade

  - name: Install Docker-py
    pip: name=docker-py

  - name: docker remove local images
    docker_image:
      name: "{{item}}"
      force_absent: yes
    with_items: 
      - "{{images.docker}}"

  - name: Tag and push docker.io images to local registry
    docker_image:
      name: "{{item}}"
      repository: "localhost:5000/{{item | regex_replace('(docker.io)/')}}"
      push: yes
      source: pull
    with_items: 
      - "{{images.docker}}"

  - name: Tag and push quay.io images to local registry
    docker_image:
      name: "{{item}}"
      repository: "localhost:5000/{{item | regex_replace('(quay.io)/')}}"
      push: yes
      source: pull
    with_items: 
      - "{{images.quay}}"

  - name: Tag and push gcr.io images to local registry
    docker_image:
      name: "{{ gcr_registry + item | regex_replace('gcr.io/')}}"
      repository: "localhost:5000/{{item | regex_replace('gcr.io/')}}"
      push: yes
      source: pull
    with_items: 
      - "{{images.gcr}}"

  - name: Tag and push k8s.gcr.io images to local registry
    docker_image:
      name: "{{ k8s_registry + item | regex_replace('k8s.gcr.io/')}}"
      repository: "localhost:5000/{{item | regex_replace('k8s.gcr.io/')}}"
      push: yes
      source: pull
    with_items: 
      - "{{images.k8s}}"