---
- name: update images
  hosts: localhost
  gather_facts: no
  become: yes
  vars_files:
  - host_vars/stx_images.yml
  - host_vars/registry.yml

  tasks:
  - debug: var=images

  - name: Install Docker Service
    apt: name=docker update_cache=yes

  - name: Install pip
    easy_install: 
      name: pip
      state: latest

  - name: Install Docker-py
    pip: name=docker-py

  - name: docker remove pulled images
    docker_image:
      name: "{{item[0]}}"
      tag: "{{item[1]}}"
      state: absent
    with_nested: 
      - "{{images.starlingx.names}}"
      - "{{images.starlingx.tags}}"
  
  - name: docker remove local images
    docker_image:
      name: "{{local_registry}}/{{item[0]}}"
      tag: "{{item[1]}}"
      state: absent
    with_nested: 
      - "{{images.starlingx.names}}"
      - "{{images.starlingx.tags}}"

  - name: Tag and push starlingx images to local registry
    docker_image:
      name: "{{item[0]}}"
      tag: "{{item[1]}}"
      repository: "{{local_registry}}/{{item[0]}}"
      push: yes
      source: pull
    with_nested: 
      - "{{images.starlingx.names}}"
      - "{{images.starlingx.tags}}"

  - name: Tag and push docker.io images to local registry
    docker_image:
      name: "{{item}}"
      repository: "{{local_registry}}/{{item | regex_replace('(docker.io)/')}}"
      push: yes
      source: pull
    with_items: 
      - "{{images.docker}}"

  - name: Tag and push quay.io images to local registry
    docker_image:
      name: "{{item}}"
      repository: "localhost:5000/{{item | regex_replace('(quay.io)/')}}"
      push: yes
      source: pull
    with_items: 
      - "{{images.quay}}"

  - name: Tag and push gcr.io images to local registry
    docker_image:
      name: "{{ gcr_registry + item | regex_replace('gcr.io/')}}"
      repository: "localhost:5000/{{item | regex_replace('gcr.io/')}}"
      push: yes
      source: pull
    with_items: 
      - "{{images.gcr}}"

  - name: Tag and push k8s.gcr.io images to local registry
    docker_image:
      name: "{{ k8s_registry + item | regex_replace('k8s.gcr.io/')}}"
      repository: "localhost:5000/{{item | regex_replace('k8s.gcr.io/')}}"
      push: yes
      source: pull
    with_items: 
      - "{{images.k8s}}"